name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'c8696863d371ab7f46e213d8f5ca923c4aef2a00'

    - name: Install Ninja for linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y ninja-build g++
    
    - name: Install Ninja for macOS
      if: runner.os == 'macOS'
      run: brew install ninja

    - name: Set VCPKG_ROOT for Unix
      if: runner.os != 'Windows'
      run: |
        echo "VCPKG_ROOT=$GITHUB_WORKSPACE/vcpkg" >> $GITHUB_ENV
      shell: bash

    - name: Install VCPKG packages
      run: vcpkg install
      
    - name: Configure CMake
      run: |
        cmake --preset=default
        cmake -S . -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure